#配置数据源
#有时候扫描不了配置文件，需要把yml内的中文注释删掉才能解决Application failed to start with classpath报错
spring:
  datasource:
    druid:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ordersystem?characterEncoding=utf8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 232521
      max-active: 20
      max-wait: 5000
      initial-size: 1
      filters: stat,log4j,wall
      validation-query: SELECT 'X'
      enable: true

      #监控配置
      stat-view-servlet:
        enabled: true
        login-username: root
        login-password: 1700502162
        url-pattern: /druid/*

  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
  #thymeleaf的配置
  thymeleaf:
    cache: false
    enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #配置redis
  redis:
    host: 127.0.0.1
    port: 6379

#配置mybatisplus
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#shiro的配置,anon的表示不拦截,authc的表示拦截
shiro:
  hash-algorithm-name: md5
  hash-iterations: 2
  anon-urls:
    - /index.html*
    - /sys/toLogin*
    - /login/login*
    - /login/getCode
    - /resources/**
  login-url: /index.html
  log-out-url: /login/logout*
  authc-ulrs:
    - /**

server:
  port: 8080

